name: Basic_CI with deploy

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master, develop ]

jobs:
  build:
    strategy:
      matrix:
        os: [
          ubuntu-latest,
          windows-latest,
          macos-15-intel,           # Intel
          macos-latest     # Apple Silicon
        ]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: mvn clean compile

      - name: Run tests
        run: mvn test

      - name: Upload test report (Surefire)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-report-${{ matrix.os }}
          path: target/surefire-reports/**

#  deploy:
#    name: Deploy to VPS
#    needs: build
#    runs-on: ubuntu-latest
#    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up JDK 17
#        uses: actions/setup-java@v4
#        with:
#          java-version: '17'
#          distribution: 'temurin'
#          cache: maven
#
#      - name: Build JAR (no tests)
#        run: mvn -B -DskipTests clean package
#
#      - name: Upload JAR to VPS (incoming)
#        uses: appleboy/scp-action@v0.1.7
#        with:
#          host: ${{ secrets.DEPLOY_HOST }}
#          username: ${{ secrets.DEPLOY_USER }}
#          key: ${{ secrets.DEPLOY_SSH_KEY }}
#          port: ${{ secrets.DEPLOY_PORT }}
#          source: "target/*.jar"
#          target: "/opt/rps/incoming/"
#          strip_components: 1
#
#      - name: Rename uploaded jar to app.jar
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.DEPLOY_HOST }}
#          username: ${{ secrets.DEPLOY_USER }}
#          key: ${{ secrets.DEPLOY_SSH_KEY }}
#          port: ${{ secrets.DEPLOY_PORT }}
#          script: |
#            set -e
#            cd /opt/rps/incoming
#            JAR=$(ls -1 *.jar | head -n 1)
#            mv -f "$JAR" app.jar
#
#      - name: Run deploy script
#        uses: appleboy/ssh-action@v1.0.3
#        with:
#          host: ${{ secrets.DEPLOY_HOST }}
#          username: ${{ secrets.DEPLOY_USER }}
#          key: ${{ secrets.DEPLOY_SSH_KEY }}
#          port: ${{ secrets.DEPLOY_PORT }}
#          script: /opt/rps/deploy.sh
